
logging:
    level:
        com.oneyear: TRACE
        
mybatis: 
   mapperLocations: classpath*:com\oneyear\bluework\mapper\*.xml
spring:
    datasource:
        name: dataSource
        url: jdbc:mysql://localhost:3306/blue_work?characterEncoding=utf8&useSSL=true
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
         cache: false